version: "3.3"

services:
  default_database:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./default_database_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"
#    networks:
#      network:
#        ipv4_address: ${DEFAULT_DATABASE_IP}

#  pgadmin:
#    container_name: simcont_pgadmin
#    image: dpage/pgadmin4:latest
#    volumes:
#      - ./pgadmin_data/:/var/lib/pgadmin
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
#      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
#    ports:
#      - "${PGADMIN_PORT}:80"
#    restart: unless-stopped
#    networks:
#      network:
#        ipv4_address: 172.20.0.3

#################################
#networks:
#  network:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.22.0.1/16
#          gateway: 172.22.0.1
