# Generated by Django 4.2.5 on 2023-11-02 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lemma', models.CharField(max_length=150)),
                ('pos', models.CharField(choices=[('NOUN', 'Noun'), ('ADJ', 'Adjective'), ('VERB', 'Verb'), ('PROPN', 'Preposition'), ('PRON', 'Pronoun'), ('CONJ', 'Conjunction'), ('PART', 'Particle'), ('INTERJ', 'Interjection'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=7)),
                ('translate', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_lemmas', models.JSONField()),
                ('source_text', models.TextField()),
                ('lang_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voc_from', to='drf_app.lang')),
                ('lang_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voc_to', to='drf_app.lang')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyLemma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_app.lemma')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_app.vocabulary')),
            ],
        ),
        migrations.AddField(
            model_name='lemma',
            name='vocabularies',
            field=models.ManyToManyField(through='drf_app.VocabularyLemma', to='drf_app.vocabulary'),
        ),
    ]
