# Generated by Django 4.2.5 on 2023-12-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='users',
            new_name='student',
        ),
    ]
