# Generated by Django 4.2.5 on 2023-11-03 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='translate',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='lang_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voc_from', to='drf_app.lang'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='lang_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voc_to', to='drf_app.lang'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='order_lemmas',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='users',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vocabularylemma',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
