# Generated by Django 4.2.5 on 2023-12-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0002_rename_users_vocabulary_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='student',
            new_name='students',
        ),
    ]
