# Generated by Django 4.2.5 on 2023-11-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0002_alter_lemma_translate_alter_vocabulary_lang_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='order_lemmas',
            field=models.JSONField(default={}),
        ),
    ]
