# Generated by Django 4.2.5 on 2023-12-08 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_app', '0003_rename_student_vocabulary_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='students',
            field=models.ManyToManyField(related_name='voc_student', through='drf_app.UserVocabulary', to=settings.AUTH_USER_MODEL),
        ),
    ]
