# Generated by Django 4.2.5 on 2023-12-08 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_app', '0004_alter_vocabulary_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVocabulary',
            new_name='StudentVocabulary',
        ),
        migrations.RenameField(
            model_name='studentvocabulary',
            old_name='through_user',
            new_name='throughStudent',
        ),
        migrations.RenameField(
            model_name='studentvocabulary',
            old_name='through_vocabulary',
            new_name='throughVocabulary',
        ),
    ]
