# Generated by Django 4.2.5 on 2023-12-08 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_app', '0005_rename_uservocabulary_studentvocabulary_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentVocabulary',
            new_name='UserVocabulary',
        ),
        migrations.RenameField(
            model_name='uservocabulary',
            old_name='throughStudent',
            new_name='throughUser',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='students',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='users',
            field=models.ManyToManyField(related_name='voc_user', through='drf_app.UserVocabulary', to=settings.AUTH_USER_MODEL),
        ),
    ]
