# Generated by Django 4.2.5 on 2023-12-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0007_rename_uservocabulary_learnervocabulary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabularylemma',
            old_name='lemma',
            new_name='throughLemma',
        ),
        migrations.RenameField(
            model_name='vocabularylemma',
            old_name='vocabulary',
            new_name='throughVocabulary',
        ),
    ]
