# Generated by Django 4.2.5 on 2023-11-03 12:37

from django.db import migrations, models
import drf_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0009_alter_vocabulary_order_lemmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='order_lemmas',
            field=models.JSONField(blank=True, null=True, validators=[drf_app.validators.validate_json]),
        ),
    ]
