# Generated by Django 4.2.5 on 2023-11-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0010_alter_vocabulary_order_lemmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='pos',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NOUN', 'Noun'), ('ADJ', 'Adjective'), ('VERB', 'Verb'), ('PROPN', 'Preposition'), ('PRON', 'Pronoun'), ('CONJ', 'Conjunction'), ('PART', 'Particle'), ('INTERJ', 'Interjection')], default='UNKNOWN', max_length=7),
        ),
    ]
