# Generated by Django 4.2.5 on 2023-12-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0010_alter_lemma_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='translate_status',
            field=models.CharField(choices=[('Rookie', 'Rookie'), ('In_Progress', 'In progress'), ('Translated', 'Translated')], default='Rookie', max_length=11),
        ),
    ]
