# Generated by Django 4.2.5 on 2023-12-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0012_education_educationlemma_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='educations',
            field=models.ManyToManyField(through='drf_app.EducationLemma', to='drf_app.education'),
        ),
    ]
