# Generated by Django 4.2.5 on 2023-11-21 11:13

from django.db import migrations, models
import drf_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0013_alter_lemma_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='translate',
            field=models.JSONField(blank=True, validators=[drf_app.validators.validate_json]),
        ),
    ]
