# Generated by Django 4.2.5 on 2023-11-23 12:37

from django.db import migrations, models
import drf_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0014_alter_lemma_translate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='order_lemmas',
            field=models.JSONField(blank=True, default=None, null=True, validators=[drf_app.validators.validate_json]),
        ),
    ]
