# Generated by Django 4.2.5 on 2023-12-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0014_alter_educationlemma_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlemma',
            name='status',
            field=models.CharField(choices=[('NE', 'New'), ('ST', 'On study'), ('LE', 'Learned')], default='NE', max_length=2),
        ),
    ]
