# Generated by Django 4.2.5 on 2023-12-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0015_alter_educationlemma_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='limit_lemmas_item',
        ),
        migrations.RemoveField(
            model_name='board',
            name='limit_lemmas_period',
        ),
        migrations.AddField(
            model_name='education',
            name='limit_lemmas_item',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='education',
            name='limit_lemmas_period',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
