# Generated by Django 4.2.5 on 2023-11-28 12:48

from django.db import migrations, models
import drf_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0015_alter_vocabulary_order_lemmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='translate',
            field=models.JSONField(blank=True, default=None, null=True, validators=[drf_app.validators.validate_json]),
        ),
    ]
