# Generated by Django 4.2.5 on 2024-01-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0016_remove_board_limit_lemmas_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='translate_status',
            field=models.CharField(choices=[('ROO', 'Rookie'), ('PRO', 'In progress'), ('TRA', 'Translated')], default='ROO', max_length=3),
        ),
    ]
