# Generated by Django 4.2.5 on 2024-02-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0018_alter_lemma_educations_alter_lemma_vocabularies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='educations',
            field=models.ManyToManyField(through='drf_app.EducationLemma', to='drf_app.education'),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='vocabularies',
            field=models.ManyToManyField(through='drf_app.VocabularyLemma', to='drf_app.vocabulary'),
        ),
    ]
