# Generated by Django 4.2.5 on 2024-04-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0019_alter_lemma_educations_alter_lemma_vocabularies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='pos',
            field=models.CharField(choices=[('X', 'other'), ('ADJ', 'adjective'), ('ADJ_SAT', 'adjective satellite'), ('ADP', 'adposition'), ('ADV', 'adverb'), ('AUX', 'auxiliary'), ('CCONJ', 'coordinating conjunction'), ('DET', 'determiner'), ('INTJ', 'interjection'), ('NOUN', 'noun'), ('NUM', 'numeral'), ('PART', 'particle'), ('PRON', 'pronoun'), ('PROPN', 'proper noun'), ('PUNCT', 'punctuation'), ('SCONJ', 'subordinating conjunction'), ('SYM', 'symbol'), ('SPACE', 'space'), ('VERB', 'verb')], default='X', max_length=7),
        ),
    ]
