# Generated by Django 4.2.5 on 2024-05-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0020_alter_lemma_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='translate_source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
